# Generated by Django 4.2.2 on 2023-06-24 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_parceiro', models.CharField(max_length=100)),
                ('endereco_parceiro', models.CharField(max_length=100)),
                ('cnpj_parceiro', models.IntegerField()),
                ('uf_cobertura', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Viability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=100)),
                ('produto', models.CharField(max_length=100)),
                ('velocidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ViabilityResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resultado_parceiro', models.CharField(max_length=50)),
                ('id_parceiro_resposta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partners.partners')),
                ('id_viabilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.viability')),
            ],
        ),
    ]
