# Generated by Django 4.2.2 on 2023-06-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partners_cnpj_parceiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='endereco_parceiro',
            field=models.CharField(max_length=255),
        ),
    ]
